### ISSUE TITLE
Bump version of node-datachannel

### ISSUE THREAD

**Issue by snimshchikov** [ThaUnknown/webrtc-polyfill#5]
Current version of node-datachannel dependency is fixed at `0.9.1`
This version has wrong order of exports (default not last)
Your fix for exports order https://github.com/murat-dogan/node-datachannel/commit/d1867d04d0f89ace3700bbebc1f2ad0798be7d5c was included in `0.9.2`
Latest version is `0.10.1`

Please bump the version of node-datachannel to at least 0.9.2

P.S. Sorry that I couldn't locate the issue, but this one should resolve it. Huge thanks for maintaining those packages

**Comment by ThaUnknown** [comment]
4fe45591cbd69629273d245ca26831005f2e6580
