### ISSUE TITLE
undefined symbol: _ZTVN10__cxxabiv117__class_type_infoE on linux only

### ISSUE THREAD

**Issue by prostarz** [ThaUnknown/webrtc-polyfill#7]
when trying to run my app on linux i get the following error that happens only on linux 

webrtc-polyfill/node_modules/node-datachannel/build/Release/node_datachannel.node: undefined symbol: _ZTVN10__cxxabiv117__class_type_infoE

**Comment by ThaUnknown** [comment]
provide reproduction and version information

**Comment by prostarz** [comment]
this is a problem with node-datachannel and is fixed by updating the package to the latest version

**Comment by ThaUnknown** [comment]
right, I should probs use dependabot here

**Comment by ThaUnknown** [comment]
I've updated to ndc 0.12, 0.20 is not stable and doesn't work correctly

**Comment by prostarz** [comment]
> I've updated to ndc 0.12, 0.20 is not stable and doesn't work correctly

TYSM :)

**Comment by ThaUnknown** [comment]
tell me if that fixes ur issues

**Comment by prostarz** [comment]
> tell me if that fixes ur issues

yes it did thank you
