### ISSUE TITLE
Cannot build with vite: Module format "cjs" does not support top-level await. Use the "es" or "system" output formats rather.

### ISSUE THREAD

**Issue by Viiprogrammer** [ThaUnknown/webrtc-polyfill#8]
After ~2.2.0 webtorrent requires webrtc-polyfill as dependency.

I solve this by patching Blob.js

Before:
```js
const _Blob = globalThis.Blob || (await import('node:buffer')).Blob

export default _Blob
```

After:
```js
import { Blob } from 'node:buffer'
const _Blob = globalThis.Blob || Blob
 
 export default _Blob
```

Complete path file:

```diff
diff --git a/lib/Blob.js b/lib/Blob.js
index bf8b40a9993fa4ab795fc410955d5318c5d400f7..c5b95decfa4fd7135ff7c9ac916947f26f0b892a 100644
--- a/lib/Blob.js
+++ b/lib/Blob.js
@@ -1,3 +1,5 @@
-const _Blob = globalThis.Blob || (await import('node:buffer')).Blob
+import { Blob } from 'node:buffer'
+const _Blob = globalThis.Blob || Blob
 
 export default _Blob
+
```

vite config for reference:
```js
import { defineConfig } from 'vite'
import createExternal from 'vite-plugin-external'
import { fileURLToPath, URL } from 'node:url'

// https://vitejs.dev/config
export default defineConfig({
  plugins: [
    createExternal({
      externals: {
        bufferutil: 'bufferutil', // For web torrent
        'node-datachannel': 'node-datachannel' // For web torrent
      }
    })
  ],
  build: {
    commonjsOptions: {
      // For web torrent
      dynamicRequireTargets: ['node_modules/default-gateway/*.js']
    }
  },
  resolve: {
    // Some libs that can run in both Web and Node.js, such as `axios`, we need to tell Vite to build them in Node.js.
    browserField: false,
    conditions: ['node'],
    mainFields: ['module', 'jsnext:main', 'jsnext'],
    alias: [
      { find: '@enums', replacement: fileURLToPath(new URL('./src/enums', import.meta.url)) }
    ]
  }
})
```
-------------

**Node:** 20.12.2
**Vite:** 5.4.10

Any solutions without direct patching module?

**Comment by ThaUnknown** [comment]
is this some vite skill issue? webpack handles compiling this to cjs just fine, so idk what the problem is

this works fine on node, browser and deno, and I'm not interested in changing it

**Comment by Viiprogrammer** [comment]
> is this some vite skill issue? webpack handles compiling this to cjs just fine, so idk what the problem is
> 
> this works fine on node, browser and deno, and I'm not interested in changing it

I'm not entirely sure, but I've tried many solutions, and nothing seems to work—except by directly patching these lines.

~~Is `await import()` really necessary in this case?~~

I'm using Electron Forge with the Vite plugin. Above is the configuration I use for the main process.

The error only visible when I set `DEBUG=*`. Compiling looks infinity without it.

I can try creating a minimal repository to reproduce the issue. Would you be interested in that?

**Comment by ThaUnknown** [comment]
if you're using electron you dont need this library, webrtc is built into the browser as such electron has it, and you should NEVER run any application specific code inside the main process as per electron's security recommendations, I recommend you run your code a 2nd browser window which the user cannot interact with and run IPC between them

**Comment by Viiprogrammer** [comment]
> if you're using electron you dont need this library, webrtc is built into the browser as such electron has it, and you should NEVER run any application specific code inside the main process as per electron's security recommendations, I recommend you run your code a 2nd browser window which the user cannot interact with and run IPC between them

WebTorrent uses `@thaunknown/simple-peer`, and it is requiring `webrtc-polyfill` in package.json dependencies. I can't avoid using it or disable it.

I use window with:
```js
contextIsolation: true,
enableRemoteModule: false,
sandbox: true,
nodeIntegration: false,
nodeIntegrationInWorker: false
``` 

I prefer to handle everything through IPC or HTTP communication with localhost. Why should I write app-specific code in the renderer process? Could you share your recommendations on this?

**Comment by Viiprogrammer** [comment]
WebTorrent is untrusted and not secure?

**Comment by ThaUnknown** [comment]
yes you can by specifying alias in module resolvers

if those are your settings then nodejs code would never be used, and the package would never be imported, so this is yet another config problem on your end

**Comment by ThaUnknown** [comment]
> WebTorrent is untrusted and not secure?

no, but user actions are, I'm not interested in teaching you attack protection models, but you can read about it on electron's security recommendations page

**Comment by ThaUnknown** [comment]
if you're not using nodejs code, you can simply use the prebuilds webtorrent provides

**Comment by Viiprogrammer** [comment]
> yes you can by specifying alias in module resolvers
> 
> if those are your settings then nodejs code would never be used, and the package would never be imported, so this is yet another config problem on your end

Hmm, I'll try adding an alias, but I feel like it's essentially the same as patching dependencies and still results in the same uncontrolled behavior.

**Comment by ThaUnknown** [comment]
as I've explained above, your build config is fucked, and this is an artifact of that problem, you're trying to solve the wrong problem

**Comment by Viiprogrammer** [comment]
> > WebTorrent is untrusted and not secure?
> 
> no, but user actions are, I'm not interested in teaching you attack protection models, but you can read about it on electron's security recommendations page

Little offtopic, maybe it will be good write in webtorrent repo, but:

One of your repositories has WebTorrent running in the [renderer](https://github.com/ThaUnknown/miru/blob/6a8d0cbea83b0cfdb6ea79eac243d55583e83414/electron/src/main/app.js#L23), with the following settings:

- contextIsolation: false ([3. Enable Context Isolation](https://www.electronjs.org/docs/latest/tutorial/security#3-enable-context-isolation))
- webSecurity: false [(6. Do not disable webSecurity)](https://www.electronjs.org/docs/latest/tutorial/security#6-do-not-disable-websecurity)
- nodeIntegration: true (Also in many rules)

Isn't this a high-risk and unsafe solution ?

**Comment by ThaUnknown** [comment]
wt-desktop is unmaintained, and I'm not its maintainer, but no, webtorrent runs in it's own tab which is local only and doesn't run any user executed actions, only strict IPC [iirc]

**Comment by ThaUnknown** [comment]
wrtc-polyfill only supports esm, either fix your own build config, or use a better cjs transpiler such as webpack as vite has poor cjs support, most of this problem stems from user error rather than problems with this package
